version: "3"
services:
  app:
    container_name: bankmanagement
    build: .
    # command: sh -c "php artisan migrate:fresh --seed --force && php artisan serve --host 0.0.0.0 --port 80"
    # entrypoint: >
    #   /bin/sh -c '        
    #     php artisan migrate:fresh --seed --force && php artisan serve --host 0.0.0.0 --port 80
    #   '
    ports:
      - ${APP_PORT}:80
    env_file:
      - .env
    network_mode: bridge
    restart: always

  db:
    container_name: bankmanagement-database
    image: mariadb
    ports:
      - ${DB_EXT_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # volumes:
    #   - './data:/var/lib/mysql'
    network_mode: bridge
    restart: always

  phpmyadmin:
    container_name: bankmanagement-phpmyadmin
    image: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    links:
      - db
    network_mode: bridge
    restart: always